name: ecommerce_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  carousel_slider_plus: ^7.1.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7

  # model
  freezed: ^3.0.6

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # core
  flutter_localization: ^0.3.2
  intl: 0.20.2
  package_info_plus: ^8.3.0

  # routing
  go_router: ^14.8.1

  # state management
  flutter_hooks: ^0.20.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0

flutter:
  generate: true
  uses-material-design: true
